<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_67efeb5e4b211',
    'title' => __('Cards', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_67f00aac8f0c4',
            'label' => __('Max cards per column', 'modularity'),
            'name' => 'cards_per_column',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 3,
            'min' => 2,
            'max' => 4,
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ),
        1 => array(
            'key' => 'field_67f00ad48f0c5',
            'label' => __('Wrap cards in background color', 'modularity'),
            'name' => 'wrap_cards_color_container',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Will only work properly if module is centered on page', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes', 'modularity'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        2 => array(
            'key' => 'field_67f00af58f0c6',
            'label' => __('Background color', 'modularity'),
            'name' => 'container_background_color',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_67f00ad48f0c5',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'none' => __('None', 'modularity'),
                'custom-color' => __('Custom color', 'modularity'),
            ),
            'default_value' => __('none', 'modularity'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_custom' => 0,
            'search_placeholder' => '',
            'allow_null' => 0,
            'ui' => 1,
            'ajax' => 0,
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_67f27a0f3028f',
            'label' => __('Custom background color', 'modularity'),
            'name' => 'container_background_color_custom',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => __('Beware WCAG rules regarding contrasts', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_67f00af58f0c6',
                        'operator' => '==',
                        'value' => 'custom-color',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'enable_opacity' => 0,
            'return_format' => 'string',
        ),
        4 => array(
            'key' => 'field_67efeb5e223df',
            'label' => __('Cards', 'modularity'),
            'name' => 'cards',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add card', 'modularity'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_67efec4d6d2ab',
                    'label' => __('Heading', 'modularity'),
                    'name' => 'heading',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_67efeb5e223df',
                ),
                1 => array(
                    'key' => 'field_67efec596d2ac',
                    'label' => __('Content', 'modularity'),
                    'name' => 'content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'parent_repeater' => 'field_67efeb5e223df',
                ),
                2 => array(
                    'key' => 'field_67efec6d6d2ad',
                    'label' => __('Image', 'modularity'),
                    'name' => 'image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'uploader' => '',
                    'return_format' => 'id',
                    'acfe_thumbnail' => 0,
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'parent_repeater' => 'field_67efeb5e223df',
                ),
                3 => array(
                    'key' => 'field_67efece36d2af',
                    'label' => __('Link', 'modularity'),
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'parent_repeater' => 'field_67efeb5e223df',
                ),
                4 => array(
                    'key' => 'field_67f289dc6aa72',
                    'label' => __('Background color', 'modularity'),
                    'name' => 'background_color',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => __('None', 'modularity'),
                        'custom-color' => __('Custom color', 'modularity'),
                    ),
                    'default_value' => __('none', 'modularity'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_67efeb5e223df',
                ),
                5 => array(
                    'key' => 'field_67f28b0cfbfbc',
                    'label' => __('Custom background color', 'modularity'),
                    'name' => 'background_color_custom',
                    'aria-label' => '',
                    'type' => 'color_picker',
                    'instructions' => __('Beware WCAG rules for contrasts and readability', 'modularity'),
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_67f289dc6aa72',
                                'operator' => '==',
                                'value' => 'custom-color',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'enable_opacity' => 0,
                    'return_format' => 'string',
                    'parent_repeater' => 'field_67efeb5e223df',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-coloredcards',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/coloredcards',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}